install.packages("RDocumentation")
install.packages("VennDiagram")

library(VennDiagram)
library(RColorBrewer)
library(ggplot2)
library(RTCGA)
library(dplyr)
library(RTCGAToolbox)
library(TCGAbiolinks)
library(data.table)
library(RDocumentation)

setwd("D:/KP/EKP_RKP/fgsea/Tcell")


#fgsea: GOBP results comparison
# CD8T in RKP vs. CD8T in EKP positive correlated
# CD8T in RKP vs. CD8T in EKP positive correlated

CD8T_RKPvs.EKP_pos_gobp = c(
  "GOBP_CYTOPLASMIC_TRANSLATION",
  "GOBP_NEGATIVE_REGULATION_OF_UBIQUITIN_PROTEIN_LIGASE_ACTIVITY",
  "GOBP_MITOCHONDRIAL_ATP_SYNTHESIS_COUPLED_PROTON_TRANSPORT",	"GOBP_ATP_SYNTHESIS_COUPLED_PROTON_TRANSPORT",
  "GOBP_AORTIC_VALVE_MORPHOGENESIS",	"GOBP_REGULATION_OF_NEURON_MATURATION",
  "GOBP_NEGATIVE_REGULATION_OF_DIGESTIVE_SYSTEM_PROCESS",	"GOBP_POSITIVE_REGULATION_OF_GASTRULATION",
  "GOBP_REGULATION_OF_ODONTOGENESIS",	"GOBP_NEGATIVE_REGULATION_OF_CALCIUM_ION_TRANSPORT_INTO_CYTOSOL",
  "GOBP_NUCLEOBASE_TRANSPORT",	"GOBP_ATP_SYNTHESIS_COUPLED_ELECTRON_TRANSPORT",
  "GOBP_T_CELL_MEDIATED_CYTOTOXICITY",	"GOBP_MITOCHONDRIAL_ELECTRON_TRANSPORT_CYTOCHROME_C_TO_OXYGEN",
  "GOBP_MITOCHONDRIAL_ELECTRON_TRANSPORT_NADH_TO_UBIQUINONE",	"GOBP_THALAMUS_DEVELOPMENT",
  "GOBP_NERVE_GROWTH_FACTOR_SIGNALING_PATHWAY",	"GOBP_NEGATIVE_REGULATION_OF_DENDRITE_MORPHOGENESIS",
  "GOBP_NEGATIVE_REGULATION_OF_PHOSPHOPROTEIN_PHOSPHATASE_ACTIVITY",
  "GOBP_REGULATION_OF_ODONTOGENESIS_OF_DENTIN_CONTAINING_TOOTH",	"GOBP_POSITIVE_THYMIC_T_CELL_SELECTION",
  "GOBP_REGULATION_OF_UBIQUITIN_PROTEIN_LIGASE_ACTIVITY",	"GOBP_OXIDATIVE_PHOSPHORYLATION",
  "GOBP_REGULATION_OF_SKELETAL_MUSCLE_TISSUE_REGENERATION",	"GOBP_REGULATION_OF_T_CELL_MEDIATED_CYTOTOXICITY",
  "GOBP_RESPIRATORY_ELECTRON_TRANSPORT_CHAIN",	"GOBP_NEGATIVE_REGULATION_OF_PROTEIN_DEPHOSPHORYLATION",
  "GOBP_THYMIC_T_CELL_SELECTION",	"GOBP_B_CELL_RECEPTOR_SIGNALING_PATHWAY",
  "GOBP_ANTIGEN_PROCESSING_AND_PRESENTATION_OF_ENDOGENOUS_PEPTIDE_ANTIGEN",
  "GOBP_POSITIVE_REGULATION_OF_T_CELL_MEDIATED_CYTOTOXICITY",	"GOBP_GAMMA_DELTA_T_CELL_ACTIVATION",
  "GOBP_NEGATIVE_REGULATION_OF_INTRACELLULAR_STEROID_HORMONE_RECEPTOR_SIGNALING_PATHWAY",
  "GOBP_ANTIGEN_PROCESSING_AND_PRESENTATION_OF_ENDOGENOUS_ANTIGEN",	"GOBP_ANTIBACTERIAL_HUMORAL_RESPONSE",
  "GOBP_LONG_CHAIN_FATTY_ACID_BIOSYNTHETIC_PROCESS",	"GOBP_NEGATIVE_REGULATION_OF_INTERLEUKIN_2_PRODUCTION",
  "GOBP_RIBOSOMAL_LARGE_SUBUNIT_ASSEMBLY",	"GOBP_REGULATION_OF_CARDIAC_MUSCLE_CELL_ACTION_POTENTIAL",
  "GOBP_POSITIVE_REGULATION_OF_ALPHA_BETA_T_CELL_PROLIFERATION",
  "GOBP_POSITIVE_REGULATION_OF_RELEASE_OF_SEQUESTERED_CALCIUM_ION_INTO_CYTOSOL",
  "GOBP_POSITIVE_REGULATION_OF_POTASSIUM_ION_TRANSPORT",	"GOBP_NUCLEAR_TRANSCRIBED_MRNA_POLY_A_TAIL_SHORTENING",
  "GOBP_ANTIGEN_PROCESSING_AND_PRESENTATION_OF_PEPTIDE_ANTIGEN_VIA_MHC_CLASS_I",
  "GOBP_NADH_DEHYDROGENASE_COMPLEX_ASSEMBLY",	"GOBP_REGULATION_OF_ACTIN_FILAMENT_BASED_MOVEMENT",
  "GOBP_AEROBIC_RESPIRATION",	"GOBP_NEGATIVE_REGULATION_OF_T_CELL_MEDIATED_IMMUNITY",
  "GOBP_REGULATION_OF_NUCLEAR_TRANSCRIBED_MRNA_CATABOLIC_PROCESS_DEADENYLATION_DEPENDENT_DECAY",
  "GOBP_REGULATION_OF_RELEASE_OF_SEQUESTERED_CALCIUM_ION_INTO_CYTOSOL",
  "GOBP_CELL_COMMUNICATION_BY_ELECTRICAL_COUPLING",	"GOBP_NEGATIVE_REGULATION_OF_RNA_SPLICING",
  "GOBP_REGULATION_OF_CALCIUM_ION_TRANSPORT_INTO_CYTOSOL",	"GOBP_T_CELL_RECEPTOR_SIGNALING_PATHWAY",
  "GOBP_POSITIVE_REGULATION_OF_POSTTRANSCRIPTIONAL_GENE_SILENCING",	"GOBP_T_CELL_DIFFERENTIATION_IN_THYMUS",
  "GOBP_REGULATION_OF_HEART_RATE_BY_CARDIAC_CONDUCTION",
  "GOBP_NEGATIVE_REGULATION_OF_ENDOTHELIAL_CELL_PROLIFERATION",
  "GOBP_NEGATIVE_REGULATION_OF_ADAPTIVE_IMMUNE_RESPONSE",
  "GOBP_NEGATIVE_REGULATION_OF_ACTIN_FILAMENT_POLYMERIZATION",	"GOBP_ATP_BIOSYNTHETIC_PROCESS",
  "GOBP_ELECTRON_TRANSPORT_CHAIN",	"GOBP_REGULATION_OF_ACTION_POTENTIAL",
  "GOBP_REGULATION_OF_ANTIGEN_RECEPTOR_MEDIATED_SIGNALING_PATHWAY",
  "GOBP_ANTIGEN_RECEPTOR_MEDIATED_SIGNALING_PATHWAY",	"GOBP_PROGRAMMED_NECROTIC_CELL_DEATH",
  "GOBP_FILOPODIUM_ASSEMBLY",	"GOBP_NEGATIVE_REGULATION_OF_LYMPHOCYTE_MEDIATED_IMMUNITY",
  "GOBP_NEGATIVE_REGULATION_OF_T_CELL_DIFFERENTIATION",
  "GOBP_NEGATIVE_REGULATION_OF_ACTIN_FILAMENT_DEPOLYMERIZATION",
  "GOBP_NEGATIVE_REGULATION_OF_ION_TRANSMEMBRANE_TRANSPORTER_ACTIVITY",
  "GOBP_NEGATIVE_REGULATION_OF_TRANSPORTER_ACTIVITY",	"GOBP_REGULATION_OF_STRIATED_MUSCLE_CONTRACTION",
  "GOBP_REGULATION_OF_PHOSPHOPROTEIN_PHOSPHATASE_ACTIVITY",
  "GOBP_POSITIVE_REGULATION_OF_CALCIUM_ION_TRANSPORT_INTO_CYTOSOL",	"GOBP_PROTON_TRANSMEMBRANE_TRANSPORT",
  "GOBP_CELLULAR_RESPIRATION",	"GOBP_NEGATIVE_REGULATION_OF_PROTEIN_POLYMERIZATION",
  "GOBP_CARDIAC_MUSCLE_CELL_ACTION_POTENTIAL",	"GOBP_SUBSTANTIA_NIGRA_DEVELOPMENT",
  "GOBP_REGULATION_OF_FILOPODIUM_ASSEMBLY",	"GOBP_ACTIN_FILAMENT_POLYMERIZATION",	"GOBP_TRANSLATIONAL_INITIATION",
  "GOBP_REGULATION_OF_NATURAL_KILLER_CELL_MEDIATED_IMMUNITY",
  "GOBP_NEGATIVE_REGULATION_OF_LYMPHOCYTE_DIFFERENTIATION",
  "GOBP_NEGATIVE_REGULATION_OF_SUPRAMOLECULAR_FIBER_ORGANIZATION",	"GOBP_SEMAPHORIN_PLEXIN_SIGNALING_PATHWAY",
  "GOBP_NEGATIVE_REGULATION_OF_EPITHELIAL_CELL_MIGRATION",	"GOBP_NEGATIVE_REGULATION_OF_DEPHOSPHORYLATION",
  "GOBP_NEGATIVE_REGULATION_OF_CALCIUM_ION_TRANSPORT",	"GOBP_RIBOSOME_ASSEMBLY",
  "GOBP_REGULATION_OF_GENE_SILENCING_BY_RNA",	"GOBP_NEGATIVE_REGULATION_OF_MRNA_CATABOLIC_PROCESS",
  "GOBP_CALCINEURIN_MEDIATED_SIGNALING",	"GOBP_NEGATIVE_REGULATION_OF_MRNA_METABOLIC_PROCESS",
  "GOBP_REGULATION_OF_T_CELL_DIFFERENTIATION",	"GOBP_SEQUESTERING_OF_CALCIUM_ION",
  "GOBP_REGULATION_OF_CARDIAC_MUSCLE_CONTRACTION",	"GOBP_REGULATION_OF_CELL_MATRIX_ADHESION",
  "GOBP_ACTIN_POLYMERIZATION_OR_DEPOLYMERIZATION",	"GOBP_REGULATION_OF_ACTIN_FILAMENT_LENGTH",
  "GOBP_REGULATION_OF_CALCIUM_ION_TRANSMEMBRANE_TRANSPORT",	"GOBP_NEGATIVE_REGULATION_OF_RNA_CATABOLIC_PROCESS",
  "GOBP_REGULATION_OF_PROTEIN_POLYMERIZATION",	"GOBP_NEGATIVE_REGULATION_OF_CYTOSKELETON_ORGANIZATION",
  "GOBP_REGULATION_OF_SODIUM_ION_TRANSPORT",	"GOBP_RNA_STABILIZATION",
  "GOBP_REGULATION_OF_MRNA_CATABOLIC_PROCESS",	"GOBP_ATP_METABOLIC_PROCESS",
  "GOBP_NEGATIVE_REGULATION_OF_PROTEIN_MODIFICATION_BY_SMALL_PROTEIN_CONJUGATION_OR_REMOVAL",
  "GOBP_REGULATION_OF_T_CELL_MEDIATED_IMMUNITY",	"GOBP_CALCIUM_ION_TRANSPORT_INTO_CYTOSOL",
  "GOBP_SPLICEOSOMAL_COMPLEX_ASSEMBLY",	"GOBP_REGULATION_OF_POTASSIUM_ION_TRANSPORT",
  "GOBP_REGULATION_OF_LYMPHOCYTE_DIFFERENTIATION",	"GOBP_POSITIVE_REGULATION_OF_ION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_ACTIN_FILAMENT_DEPOLYMERIZATION",	"GOBP_POSITIVE_REGULATION_OF_PROTEIN_POLYMERIZATION",
  "GOBP_REGULATION_OF_MRNA_SPLICING_VIA_SPLICEOSOME",	"GOBP_T_CELL_MEDIATED_IMMUNITY",
  "GOBP_NEGATIVE_REGULATION_OF_ION_TRANSMEMBRANE_TRANSPORT",	"GOBP_REGULATION_OF_MRNA_METABOLIC_PROCESS",
  "GOBP_ALTERNATIVE_MRNA_SPLICING_VIA_SPLICEOSOME",	"GOBP_REGULATION_OF_TRANSLATIONAL_INITIATION",
  "GOBP_GENE_SILENCING_BY_RNA",	"GOBP_ACTIN_MEDIATED_CELL_CONTRACTION",	"GOBP_T_CELL_MIGRATION",
  "GOBP_NUCLEAR_TRANSCRIBED_MRNA_CATABOLIC_PROCESS",	"GOBP_LAMELLIPODIUM_ASSEMBLY",
  "GOBP_MITOCHONDRIAL_RESPIRATORY_CHAIN_COMPLEX_ASSEMBLY",	"GOBP_NATURAL_KILLER_CELL_ACTIVATION",
  "GOBP_INTEGRIN_MEDIATED_SIGNALING_PATHWAY",	"GOBP_RNA_SPLICING_VIA_TRANSESTERIFICATION_REACTIONS",
  "GOBP_REGULATION_OF_CELL_SUBSTRATE_JUNCTION_ORGANIZATION",	"GOBP_ACTIVATION_OF_IMMUNE_RESPONSE",
  "GOBP_MRNA_CATABOLIC_PROCESS",	"GOBP_NUCLEAR_TRANSCRIBED_MRNA_CATABOLIC_PROCESS_DEADENYLATION_DEPENDENT_DECAY",
  "GOBP_ENERGY_DERIVATION_BY_OXIDATION_OF_ORGANIC_COMPOUNDS",	"GOBP_REGULATION_OF_PROTEIN_DEPHOSPHORYLATION",
  "GOBP_REGULATION_OF_ENDOTHELIAL_CELL_MIGRATION",	"GOBP_POSITIVE_REGULATION_OF_MRNA_METABOLIC_PROCESS",
  "GOBP_RNA_DESTABILIZATION",	"GOBP_SUBSTRATE_ADHESION_DEPENDENT_CELL_SPREADING",
  "GOBP_RIBONUCLEOSIDE_TRIPHOSPHATE_BIOSYNTHETIC_PROCESS",	"GOBP_RIBONUCLEOPROTEIN_COMPLEX_SUBUNIT_ORGANIZATION",
  "GOBP_PROTEIN_POLYMERIZATION",	"GOBP_IMMUNE_RESPONSE_REGULATING_CELL_SURFACE_RECEPTOR_SIGNALING_PATHWAY",
  "GOBP_REGULATION_OF_ACTIN_FILAMENT_ORGANIZATION",	"GOBP_NEURAL_PRECURSOR_CELL_PROLIFERATION",
  "GOBP_REGULATION_OF_PROTEIN_MODIFICATION_BY_SMALL_PROTEIN_CONJUGATION_OR_REMOVAL",
  "GOBP_LAMELLIPODIUM_ORGANIZATION",	"GOBP_POSITIVE_REGULATION_OF_PROTEIN_LOCALIZATION_TO_NUCLEUS",
  "GOBP_CYTOSOLIC_CALCIUM_ION_TRANSPORT",	"GOBP_POSITIVE_REGULATION_OF_TRANSLATION",
  "GOBP_REGULATION_OF_MRNA_PROCESSING",	"GOBP_T_CELL_ACTIVATION",
  "GOBP_NEGATIVE_REGULATION_OF_CANONICAL_WNT_SIGNALING_PATHWAY",	"GOBP_REGULATION_OF_T_CELL_ACTIVATION",
  "GOBP_POSITIVE_REGULATION_OF_TRANSPORTER_ACTIVITY",	"GOBP_RNA_DEPENDENT_DNA_BIOSYNTHETIC_PROCESS",
  "GOBP_ENDOPLASMIC_RETICULUM_TO_GOLGI_VESICLE_MEDIATED_TRANSPORT",	"GOBP_ENDOTHELIAL_CELL_MIGRATION",
  "GOBP_LYMPHOCYTE_MIGRATION",	"GOBP_DENDRITIC_SPINE_DEVELOPMENT",
  "GOBP_REGULATION_OF_ACTIN_FILAMENT_BASED_PROCESS",	"GOBP_REGULATION_OF_SUPRAMOLECULAR_FIBER_ORGANIZATION",
  "GOBP_POSITIVE_REGULATION_OF_LEUKOCYTE_CELL_CELL_ADHESION",	"GOBP_RNA_LOCALIZATION",
  "GOBP_NEGATIVE_REGULATION_OF_PROTEIN_CONTAINING_COMPLEX_ASSEMBLY",	"GOBP_ACTIN_CYTOSKELETON_REORGANIZATION",
  "GOBP_T_CELL_PROLIFERATION",	"GOBP_NEGATIVE_REGULATION_OF_IMMUNE_EFFECTOR_PROCESS",
  "GOBP_T_CELL_DIFFERENTIATION",	"GOBP_CHROMATIN_ASSEMBLY_OR_DISASSEMBLY",
  "GOBP_REGULATION_OF_PROTEIN_LOCALIZATION_TO_PLASMA_MEMBRANE",	"GOBP_RNA_SPLICING",
  "GOBP_REGULATION_OF_EPITHELIAL_CELL_MIGRATION",	"GOBP_REGULATION_OF_CELL_SUBSTRATE_ADHESION",
  "GOBP_BLOOD_VESSEL_ENDOTHELIAL_CELL_MIGRATION",	"GOBP_RNA_CATABOLIC_PROCESS",
  "GOBP_POSITIVE_REGULATION_OF_CELLULAR_AMIDE_METABOLIC_PROCESS",	"GOBP_NEGATIVE_REGULATION_OF_ION_TRANSPORT",
  "GOBP_MRNA_PROCESSING",	"GOBP_REGULATION_OF_PROTEIN_LOCALIZATION_TO_CELL_PERIPHERY",
  "GOBP_REGULATION_OF_LYMPHOCYTE_MEDIATED_IMMUNITY",	"GOBP_REGULATION_OF_CATION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_CALCIUM_ION_TRANSMEMBRANE_TRANSPORT",	"GOBP_POSTTRANSCRIPTIONAL_REGULATION_OF_GENE_EXPRESSION",
  "GOBP_REGULATION_OF_METAL_ION_TRANSPORT",	"GOBP_ALPHA_BETA_T_CELL_DIFFERENTIATION",	"GOBP_DNA_PACKAGING",
  "GOBP_LEUKOCYTE_CELL_CELL_ADHESION",	"GOBP_ESTABLISHMENT_OF_RNA_LOCALIZATION",
  "GOBP_POSITIVE_REGULATION_OF_BINDING",	"GOBP_REGULATION_OF_CELLULAR_COMPONENT_SIZE",
  "GOBP_POSITIVE_REGULATION_OF_PROTEIN_MODIFICATION_BY_SMALL_PROTEIN_CONJUGATION_OR_REMOVAL",
  "GOBP_REGULATION_OF_CALCIUM_ION_TRANSPORT",	"GOBP_NUCLEAR_EXPORT",	"GOBP_ALPHA_BETA_T_CELL_ACTIVATION",
  "GOBP_REGULATION_OF_ANATOMICAL_STRUCTURE_SIZE",	"GOBP_ENDOTHELIAL_CELL_PROLIFERATION",
  "GOBP_NEGATIVE_REGULATION_OF_CELLULAR_AMIDE_METABOLIC_PROCESS",	"GOBP_REGULATION_OF_DEPHOSPHORYLATION",
  "GOBP_REGULATION_OF_CELLULAR_AMIDE_METABOLIC_PROCESS",	"GOBP_CELL_KILLING",
  "GOBP_RIBONUCLEOPROTEIN_COMPLEX_BIOGENESIS",	"GOBP_REGULATION_OF_TRANSPORTER_ACTIVITY",
  "GOBP_CHROMATIN_ORGANIZATION",	"GOBP_CHROMATIN_REMODELING",	"GOBP_REGULATION_OF_RNA_SPLICING",
  "GOBP_POSITIVE_REGULATION_OF_WNT_SIGNALING_PATHWAY",	"GOBP_REGULATION_OF_PROTEIN_LOCALIZATION_TO_NUCLEUS",
  "GOBP_REGULATION_OF_ADAPTIVE_IMMUNE_RESPONSE",	"GOBP_MRNA_TRANSPORT",	"GOBP_ACTIN_FILAMENT_ORGANIZATION",
  "GOBP_PROTEIN_POLYUBIQUITINATION",	"GOBP_PROTEIN_FOLDING",	"GOBP_CELL_MATRIX_ADHESION",
  "GOBP_TISSUE_MIGRATION",	"GOBP_RHO_PROTEIN_SIGNAL_TRANSDUCTION",
  "GOBP_POSITIVE_REGULATION_OF_CELL_CELL_ADHESION",	"GOBP_AMEBOIDAL_TYPE_CELL_MIGRATION",
  "GOBP_CELL_CELL_JUNCTION_ORGANIZATION",	"GOBP_ESTABLISHMENT_OR_MAINTENANCE_OF_CELL_POLARITY",
  "GOBP_CALCIUM_ION_TRANSPORT",	"GOBP_REGULATION_OF_INNATE_IMMUNE_RESPONSE",
  "GOBP_NEGATIVE_REGULATION_OF_WNT_SIGNALING_PATHWAY",	"GOBP_REGULATION_OF_WNT_SIGNALING_PATHWAY",
  "GOBP_PROTEIN_DEPHOSPHORYLATION",	"GOBP_REGULATION_OF_LYMPHOCYTE_ACTIVATION",	"GOBP_NUCLEAR_TRANSPORT",
  "GOBP_GENERATION_OF_PRECURSOR_METABOLITES_AND_ENERGY",	"GOBP_LEUKOCYTE_PROLIFERATION",
  "GOBP_GOLGI_VESICLE_TRANSPORT",	"GOBP_POSITIVE_REGULATION_OF_CELL_ADHESION",
  "GOBP_PROTEIN_LOCALIZATION_TO_PLASMA_MEMBRANE",	"GOBP_REGULATION_OF_CANONICAL_WNT_SIGNALING_PATHWAY",
  "GOBP_POSITIVE_REGULATION_OF_TRANSMEMBRANE_TRANSPORT",	"GOBP_REGULATION_OF_ION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_PROTEIN_LOCALIZATION_TO_CELL_PERIPHERY",	"GOBP_REGULATION_OF_SMALL_GTPASE_MEDIATED_SIGNAL_TRANSDUCTION",
  "GOBP_BONE_DEVELOPMENT",	"GOBP_CANONICAL_WNT_SIGNALING_PATHWAY",
  "GOBP_NEGATIVE_REGULATION_OF_CELLULAR_CATABOLIC_PROCESS",	"GOBP_POSITIVE_REGULATION_OF_IMMUNE_RESPONSE",
  "GOBP_REGULATION_OF_CELL_CELL_ADHESION",	"GOBP_CELL_CELL_SIGNALING_BY_WNT",
  "GOBP_NEGATIVE_REGULATION_OF_IMMUNE_RESPONSE",	"GOBP_NEGATIVE_REGULATION_OF_PROTEIN_MODIFICATION_PROCESS",
  "GOBP_REGULATION_OF_CELLULAR_PROTEIN_CATABOLIC_PROCESS",	"GOBP_HOMEOSTASIS_OF_NUMBER_OF_CELLS",
  "GOBP_REGULATION_OF_T_CELL_PROLIFERATION",	"GOBP_RIBOSOME_BIOGENESIS",
  "GOBP_NON_MEMBRANE_BOUNDED_ORGANELLE_ASSEMBLY",	"GOBP_DNA_CONFORMATION_CHANGE",	"GOBP_REGULATION_OF_BINDING",
  "GOBP_PEPTIDYL_SERINE_MODIFICATION",	"GOBP_PROTEIN_STABILIZATION",
  "GOBP_REGULATION_OF_UBIQUITIN_DEPENDENT_PROTEIN_CATABOLIC_PROCESS",	"GOBP_REGULATION_OF_INTRACELLULAR_TRANSPORT"
  ,	"GOBP_LYMPHOCYTE_MEDIATED_IMMUNITY",	"GOBP_CELL_SUBSTRATE_ADHESION",	"GOBP_MONONUCLEAR_CELL_DIFFERENTIATION",
  "GOBP_NEGATIVE_REGULATION_OF_CELLULAR_MACROMOLECULE_BIOSYNTHETIC_PROCESS",	"GOBP_ADAPTIVE_IMMUNE_RESPONSE",
  "GOBP_NUCLEOBASE_CONTAINING_COMPOUND_TRANSPORT",
  "GOBP_CELL_SURFACE_RECEPTOR_SIGNALING_PATHWAY_INVOLVED_IN_CELL_CELL_SIGNALING",
  "GOBP_REGULATION_OF_CYTOSKELETON_ORGANIZATION",	"GOBP_REGULATION_OF_CHROMOSOME_ORGANIZATION",
  "GOBP_REGULATION_OF_PROTEIN_CATABOLIC_PROCESS",	"GOBP_B_CELL_ACTIVATION",	"GOBP_REGULATION_OF_GTPASE_ACTIVITY",
  "GOBP_HISTONE_MODIFICATION",	"GOBP_NEGATIVE_REGULATION_OF_CATABOLIC_PROCESS",	"GOBP_VIRAL_PROCESS",
  "GOBP_REGULATION_OF_LEUKOCYTE_DIFFERENTIATION",	"GOBP_NEGATIVE_REGULATION_OF_IMMUNE_SYSTEM_PROCESS",
  "GOBP_NEGATIVE_REGULATION_OF_CELL_ADHESION",	"GOBP_REGULATION_OF_INTRACELLULAR_PROTEIN_TRANSPORT",
  "GOBP_SMALL_GTPASE_MEDIATED_SIGNAL_TRANSDUCTION",	"GOBP_RRNA_METABOLIC_PROCESS",
  "GOBP_PROTEASOMAL_PROTEIN_CATABOLIC_PROCESS",	"GOBP_REGULATION_OF_HEMOPOIESIS",
  "GOBP_PROTEIN_LOCALIZATION_TO_NUCLEUS",	"GOBP_POSITIVE_REGULATION_OF_CELL_ACTIVATION",
  "GOBP_REGULATION_OF_PROTEIN_CONTAINING_COMPLEX_ASSEMBLY",	"GOBP_RESPONSE_TO_VIRUS",
  "GOBP_NEGATIVE_REGULATION_OF_PHOSPHORUS_METABOLIC_PROCESS",	"GOBP_IMMUNE_RESPONSE_REGULATING_SIGNALING_PATHWAY",
  "GOBP_NEGATIVE_REGULATION_OF_CELL_DIFFERENTIATION",	"GOBP_POSITIVE_REGULATION_OF_ORGANELLE_ORGANIZATION",
  "GOBP_ESTABLISHMENT_OF_PROTEIN_LOCALIZATION_TO_ORGANELLE",	"GOBP_DEPHOSPHORYLATION",
  "GOBP_REGULATION_OF_RESPONSE_TO_BIOTIC_STIMULUS",	"GOBP_IMMUNE_EFFECTOR_PROCESS",
  "GOBP_ORGANIC_CYCLIC_COMPOUND_CATABOLIC_PROCESS",
  "GOBP_PROTEASOME_MEDIATED_UBIQUITIN_DEPENDENT_PROTEIN_CATABOLIC_PROCESS",
  "GOBP_CELLULAR_NITROGEN_COMPOUND_CATABOLIC_PROCESS",	"GOBP_POSITIVE_REGULATION_OF_CATABOLIC_PROCESS",
  "GOBP_REGULATION_OF_DNA_METABOLIC_PROCESS",	"GOBP_LEUKOCYTE_DIFFERENTIATION",
  "GOBP_POSITIVE_REGULATION_OF_HYDROLASE_ACTIVITY",	"GOBP_CELLULAR_RESPONSE_TO_HORMONE_STIMULUS",
  "GOBP_REGULATION_OF_ION_TRANSPORT")


CD4T_RKPvs.EKP_pos_gobp = c(
  "GOBP_CYTOPLASMIC_TRANSLATION","GOBP_NEGATIVE_REGULATION_OF_UBIQUITIN_PROTEIN_LIGASE_ACTIVITY",
  "GOBP_NEGATIVE_REGULATION_OF_UBIQUITIN_PROTEIN_TRANSFERASE_ACTIVITY",
  "GOBP_NEGATIVE_REGULATION_OF_DIGESTIVE_SYSTEM_PROCESS",	"GOBP_THYMIC_T_CELL_SELECTION",
  "GOBP_T_CELL_DIFFERENTIATION_IN_THYMUS",
  "GOBP_POSITIVE_REGULATION_OF_SIGNAL_TRANSDUCTION_BY_P53_CLASS_MEDIATOR",
  "GOBP_REGULATION_OF_UBIQUITIN_PROTEIN_LIGASE_ACTIVITY",	"GOBP_REGULATION_OF_T_CELL_CHEMOTAXIS",
  "GOBP_NEGATIVE_REGULATION_OF_POTASSIUM_ION_TRANSPORT",	"GOBP_COCHLEA_MORPHOGENESIS",
  "GOBP_NEGATIVE_REGULATION_OF_POTASSIUM_ION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_NEGATIVE_REGULATION_OF_ION_TRANSMEMBRANE_TRANSPORTER_ACTIVITY",
  "GOBP_REGULATION_OF_NATURAL_KILLER_CELL_MEDIATED_IMMUNITY",	"GOBP_AORTIC_VALVE_MORPHOGENESIS",
  "GOBP_POSITIVE_REGULATION_OF_NATURAL_KILLER_CELL_MEDIATED_CYTOTOXICITY",
  "GOBP_RIBOSOMAL_LARGE_SUBUNIT_ASSEMBLY",	"GOBP_T_CELL_RECEPTOR_SIGNALING_PATHWAY",
  "GOBP_HEMATOPOIETIC_STEM_CELL_MIGRATION",	"GOBP_POSITIVE_REGULATION_OF_NATURAL_KILLER_CELL_MEDIATED_IMMUNITY",
  "GOBP_NEGATIVE_REGULATION_OF_INTRACELLULAR_STEROID_HORMONE_RECEPTOR_SIGNALING_PATHWAY",
  "GOBP_NEGATIVE_REGULATION_OF_CELL_KILLING",	"GOBP_POSITIVE_REGULATION_OF_POTASSIUM_ION_TRANSPORT",
  "GOBP_MICROVILLUS_ASSEMBLY",	"GOBP_STEM_CELL_DIVISION",	"GOBP_T_CELL_MIGRATION",
  "GOBP_INTERLEUKIN_2_PRODUCTION",	"GOBP_CARDIAC_MUSCLE_CELL_ACTION_POTENTIAL",
  "GOBP_REGULATION_OF_ACTIN_FILAMENT_BASED_MOVEMENT",	"GOBP_REGULATION_OF_STRIATED_MUSCLE_CONTRACTION",
  "GOBP_ANTIGEN_RECEPTOR_MEDIATED_SIGNALING_PATHWAY",	"GOBP_NATURAL_KILLER_CELL_ACTIVATION",
  "GOBP_LYMPHOCYTE_MIGRATION",	"GOBP_REGULATION_OF_SODIUM_ION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_T_CELL_MEDIATED_CYTOTOXICITY",	"GOBP_ATP_SYNTHESIS_COUPLED_ELECTRON_TRANSPORT",
  "GOBP_NEGATIVE_REGULATION_OF_LYMPHOCYTE_MEDIATED_IMMUNITY",
  "GOBP_REGULATION_OF_ANTIGEN_RECEPTOR_MEDIATED_SIGNALING_PATHWAY",	"GOBP_REGULATION_OF_T_CELL_MIGRATION",
  "GOBP_REGULATION_OF_CARDIAC_MUSCLE_CONTRACTION",	"GOBP_POSITIVE_REGULATION_OF_PROTEIN_POLYMERIZATION",
  "GOBP_NEGATIVE_REGULATION_OF_ION_TRANSMEMBRANE_TRANSPORT",	"GOBP_RIBOSOME_ASSEMBLY",
  "GOBP_REGULATION_OF_CELL_MATRIX_ADHESION",	"GOBP_POSITIVE_REGULATION_OF_ION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_REGULATION_OF_CALCIUM_ION_TRANSMEMBRANE_TRANSPORTER_ACTIVITY",	"GOBP_CHROMATIN_ASSEMBLY_OR_DISASSEMBLY",
  "GOBP_T_CELL_MEDIATED_IMMUNITY",	"GOBP_ACTIN_FILAMENT_POLYMERIZATION",
  "GOBP_REGULATION_OF_T_CELL_DIFFERENTIATION",	"GOBP_REGULATION_OF_SODIUM_ION_TRANSPORT",
  "GOBP_NEGATIVE_REGULATION_OF_TRANSPORTER_ACTIVITY",	"GOBP_RESPIRATORY_ELECTRON_TRANSPORT_CHAIN",
  "GOBP_REGULATION_OF_INTRACELLULAR_STEROID_HORMONE_RECEPTOR_SIGNALING_PATHWAY",	"GOBP_OXIDATIVE_PHOSPHORYLATION",
  "GOBP_REGULATION_OF_LYMPHOCYTE_DIFFERENTIATION",	"GOBP_REGULATION_OF_PROTEIN_POLYMERIZATION",
  "GOBP_REGULATION_OF_T_CELL_MEDIATED_IMMUNITY",	"GOBP_REGULATION_OF_ACTIN_FILAMENT_LENGTH",
  "GOBP_CHROMATIN_REMODELING",	"GOBP_REGULATION_OF_CALCIUM_ION_TRANSMEMBRANE_TRANSPORT",	"GOBP_DNA_PACKAGING",
  "GOBP_CARDIAC_CONDUCTION",	"GOBP_DIGESTIVE_SYSTEM_DEVELOPMENT",
  "GOBP_POSITIVE_REGULATION_OF_TRANSPORTER_ACTIVITY",	"GOBP_B_CELL_RECEPTOR_SIGNALING_PATHWAY",
  "GOBP_ACTIN_POLYMERIZATION_OR_DEPOLYMERIZATION",	"GOBP_ESTABLISHMENT_OR_MAINTENANCE_OF_CELL_POLARITY",
  "GOBP_CHROMATIN_ORGANIZATION",	"GOBP_T_CELL_DIFFERENTIATION",	"GOBP_HISTONE_DEACETYLATION",
  "GOBP_REGULATION_OF_ACTIN_FILAMENT_ORGANIZATION",	"GOBP_PROTEIN_POLYMERIZATION",
  "GOBP_IMMUNE_RESPONSE_REGULATING_CELL_SURFACE_RECEPTOR_SIGNALING_PATHWAY",
  "GOBP_NEGATIVE_REGULATION_OF_WNT_SIGNALING_PATHWAY",	"GOBP_T_CELL_ACTIVATION",	"GOBP_TRANSLATIONAL_INITIATION",
  "GOBP_REGULATION_OF_T_CELL_ACTIVATION",	"GOBP_REGULATION_OF_LYMPHOCYTE_MEDIATED_IMMUNITY",
  "GOBP_ESTABLISHMENT_OF_CELL_POLARITY",	"GOBP_ACTIVATION_OF_IMMUNE_RESPONSE",	"GOBP_T_CELL_PROLIFERATION",
  "GOBP_REGULATION_OF_ACTIN_FILAMENT_BASED_PROCESS",	"GOBP_POSITIVE_REGULATION_OF_LEUKOCYTE_CELL_CELL_ADHESION",
  "GOBP_DNA_CONFORMATION_CHANGE",	"GOBP_REGULATION_OF_CATION_TRANSMEMBRANE_TRANSPORT",
  "GOBP_LEUKOCYTE_CELL_CELL_ADHESION",	"GOBP_POSITIVE_REGULATION_OF_BINDING",
  "GOBP_REGULATION_OF_CELL_SUBSTRATE_ADHESION",	"GOBP_CELL_MATRIX_ADHESION",	"GOBP_NUCLEAR_EXPORT",
  "GOBP_AEROBIC_RESPIRATION",	"GOBP_REGULATION_OF_PROTEIN_MODIFICATION_BY_SMALL_PROTEIN_CONJUGATION_OR_REMOVAL",
  "GOBP_REGULATION_OF_TRANSPORTER_ACTIVITY",	"GOBP_RIBONUCLEOPROTEIN_COMPLEX_SUBUNIT_ORGANIZATION",
  "GOBP_ALPHA_BETA_T_CELL_ACTIVATION",	"GOBP_ACTIN_FILAMENT_ORGANIZATION",
  "GOBP_CALCIUM_ION_TRANSMEMBRANE_TRANSPORT",	"GOBP_NEGATIVE_REGULATION_OF_SUPRAMOLECULAR_FIBER_ORGANIZATION",
  "GOBP_REGULATION_OF_SUPRAMOLECULAR_FIBER_ORGANIZATION",	"GOBP_REGULATION_OF_CELLULAR_COMPONENT_SIZE",
  "GOBP_INTRACELLULAR_RECEPTOR_SIGNALING_PATHWAY",	"GOBP_REGULATION_OF_LYMPHOCYTE_ACTIVATION",
  "GOBP_REGULATION_OF_INNATE_IMMUNE_RESPONSE",	"GOBP_REGULATION_OF_WNT_SIGNALING_PATHWAY",
  "GOBP_REGULATION_OF_ION_TRANSMEMBRANE_TRANSPORT",	"GOBP_MRNA_CATABOLIC_PROCESS",
  "GOBP_REGULATION_OF_ANATOMICAL_STRUCTURE_SIZE",	"GOBP_CELLULAR_RESPIRATION",	"GOBP_CELL_SUBSTRATE_ADHESION",
  "GOBP_CALCIUM_ION_TRANSPORT",	"GOBP_POSITIVE_REGULATION_OF_CELL_CELL_ADHESION",
  "GOBP_POSITIVE_REGULATION_OF_CELL_ADHESION",	"GOBP_MONONUCLEAR_CELL_DIFFERENTIATION",
  "GOBP_LYMPHOCYTE_MEDIATED_IMMUNITY",	"GOBP_CELL_CELL_SIGNALING_BY_WNT",	"GOBP_PROTEIN_DEPHOSPHORYLATION",
  "GOBP_ADAPTIVE_IMMUNE_RESPONSE",	"GOBP_NUCLEAR_TRANSPORT",	"GOBP_REGULATION_OF_CELL_CELL_ADHESION",
  "GOBP_REGULATION_OF_HEMOPOIESIS",	"GOBP_REGULATION_OF_SMALL_GTPASE_MEDIATED_SIGNAL_TRANSDUCTION",
  "GOBP_REGULATION_OF_METAL_ION_TRANSPORT",	"GOBP_HISTONE_MODIFICATION",
  "GOBP_CELL_MORPHOGENESIS_INVOLVED_IN_NEURON_DIFFERENTIATION",	"GOBP_REGULATION_OF_CYTOSKELETON_ORGANIZATION",
  "GOBP_POSTTRANSCRIPTIONAL_REGULATION_OF_GENE_EXPRESSION",	"GOBP_POSITIVE_REGULATION_OF_IMMUNE_RESPONSE",
  "GOBP_RIBONUCLEOPROTEIN_COMPLEX_BIOGENESIS",	"GOBP_REGULATION_OF_CELLULAR_AMIDE_METABOLIC_PROCESS",
  "GOBP_CELL_SURFACE_RECEPTOR_SIGNALING_PATHWAY_INVOLVED_IN_CELL_CELL_SIGNALING",	"GOBP_CELL_PART_MORPHOGENESIS",
  "GOBP_NEGATIVE_REGULATION_OF_PROTEIN_MODIFICATION_PROCESS")

data_1 = CD8T_RKPvs.EKP_pos_gobp 
data_2 = CD4T_RKPvs.EKP_pos_gobp

set1 = as.list(data_1)
set2 = as.list(data_2)

venn.diagram(
  x = list(set1, set2),
  category.names = c("" , ""),
  filename = 'RKP_CD8T_and_CD4T_positive_GOBP_venn_diagramm.png',
  output=TRUE,
  
  # Output features
  imagetype="png" ,
  height = 480 , 
  width = 480 , 
  resolution = 300,
  compression = "lzw",
  
  # Circles
  lwd = 2,
  lty = 'blank',
  fill = c('lightpink2','lightseagreen'),
  cat.pos=c(-10, 0),
  # Numbers
  cex = .6,
  fontface = "bold",
  fontfamily = "sans"
)

#fgsea: REACTOME results comparison


CD8T_RKPvs.EKP_pos_reactome = c("REACTOME_EUKARYOTIC_TRANSLATION_ELONGATION",
                           "REACTOME_RESPONSE_OF_EIF2AK4_GCN2_TO_AMINO_ACID_DEFICIENCY",	"REACTOME_SELENOAMINO_ACID_METABOLISM",	"REACTOME_SRP_DEPENDENT_COTRANSLATIONAL_PROTEIN_TARGETING_TO_MEMBRANE",	"REACTOME_EUKARYOTIC_TRANSLATION_INITIATION",	"REACTOME_NONSENSE_MEDIATED_DECAY_NMD",	"REACTOME_FORMATION_OF_ATP_BY_CHEMIOSMOTIC_COUPLING",	"REACTOME_ACTIVATION_OF_THE_MRNA_UPON_BINDING_OF_THE_CAP_BINDING_COMPLEX_AND_EIFS_AND_SUBSEQUENT_BINDING_TO_43S",	"REACTOME_CELLULAR_RESPONSE_TO_STARVATION",	"REACTOME_REGULATION_OF_EXPRESSION_OF_SLITS_AND_ROBOS",
                           "REACTOME_INFLUENZA_INFECTION",	"REACTOME_SIGNALING_BY_ROBO_RECEPTORS",	"REACTOME_RUNX3_REGULATES_YAP1_MEDIATED_TRANSCRIPTION",	"REACTOME_GENERATION_OF_SECOND_MESSENGER_MOLECULES",	"REACTOME_FOLDING_OF_ACTIN_BY_CCT_TRIC",	"REACTOME_CRISTAE_FORMATION",	"REACTOME_RESPIRATORY_ELECTRON_TRANSPORT_ATP_SYNTHESIS_BY_CHEMIOSMOTIC_COUPLING_AND_HEAT_PRODUCTION_BY_UNCOUPLING_PROTEINS",	"REACTOME_METABOLISM_OF_ANGIOTENSINOGEN_TO_ANGIOTENSINS",	"REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_27_HYDROXYCHOLESTEROL",
                           "REACTOME_CALCINEURIN_ACTIVATES_NFAT",	"REACTOME_REGULATION_OF_PTEN_STABILITY_AND_ACTIVITY",	"REACTOME_NERVOUS_SYSTEM_DEVELOPMENT",	"REACTOME_AUF1_HNRNP_D0_BINDS_AND_DESTABILIZES_MRNA",	"REACTOME_EPHA_MEDIATED_GROWTH_CONE_COLLAPSE",	"REACTOME_RUNX3_REGULATES_IMMUNE_RESPONSE_AND_CELL_MIGRATION",	"REACTOME_RRNA_PROCESSING",	"REACTOME_DEGRADATION_OF_AXIN",	"REACTOME_NEGATIVE_REGULATION_OF_NOTCH4_SIGNALING",	"REACTOME_MITOTIC_TELOPHASE_CYTOKINESIS",	"REACTOME_INCRETIN_SYNTHESIS_SECRETION_AND_INACTIVATION",	"REACTOME_RESPIRATORY_ELECTRON_TRANSPORT",	"REACTOME_NEF_AND_SIGNAL_TRANSDUCTION",	"REACTOME_DEGRADATION_OF_DVL",	"REACTOME_CROSS_PRESENTATION_OF_SOLUBLE_EXOGENOUS_ANTIGENS_ENDOSOMES",	"REACTOME_COMPLEX_I_BIOGENESIS",	"REACTOME_REGULATION_OF_RAS_BY_GAPS",	"REACTOME_ASYMMETRIC_LOCALIZATION_OF_PCP_PROTEINS",	"REACTOME_REGULATION_OF_RUNX3_EXPRESSION_AND_ACTIVITY",	"REACTOME_TCR_SIGNALING",
                           "REACTOME_SYNTHESIS_SECRETION_AND_INACTIVATION_OF_GLUCAGON_LIKE_PEPTIDE_1_GLP_1",	"REACTOME_MAPK6_MAPK4_SIGNALING",	"REACTOME_STABILIZATION_OF_P53",	"REACTOME_TRANSLATION",	"REACTOME_EPHB_MEDIATED_FORWARD_SIGNALING",	"REACTOME_REGULATION_OF_HMOX1_EXPRESSION_AND_ACTIVITY",	"REACTOME_METABOLISM_OF_AMINO_ACIDS_AND_DERIVATIVES",	"REACTOME_ALK_MUTANTS_BIND_TKIS",	"REACTOME_HEDGEHOG_ON_STATE",	"REACTOME_GENE_AND_PROTEIN_EXPRESSION_BY_JAK_STAT_SIGNALING_AFTER_INTERLEUKIN_12_STIMULATION",	"REACTOME_PCP_CE_PATHWAY",	"REACTOME_COHESIN_LOADING_ONTO_CHROMATIN",
                           "REACTOME_BETA_CATENIN_INDEPENDENT_WNT_SIGNALING",	"REACTOME_SYNTHESIS_SECRETION_AND_INACTIVATION_OF_GLUCOSE_DEPENDENT_INSULINOTROPIC_POLYPEPTIDE_GIP",	"REACTOME_GLUCAGON_SIGNALING_IN_METABOLIC_REGULATION",	"REACTOME_RUNX1_REGULATES_TRANSCRIPTION_OF_GENES_INVOLVED_IN_DIFFERENTIATION_OF_HSCS",
                           "REACTOME_DEGRADATION_OF_GLI1_BY_THE_PROTEASOME",	"REACTOME_SEMA3A_PAK_DEPENDENT_AXON_REPULSION",	"REACTOME_DEGRADATION_OF_BETA_CATENIN_BY_THE_DESTRUCTION_COMPLEX",	"REACTOME_HEDGEHOG_LIGAND_BIOGENESIS",	"REACTOME_INTERACTION_BETWEEN_L1_AND_ANKYRINS",	"REACTOME_REGULATION_OF_MRNA_STABILITY_BY_PROTEINS_THAT_BIND_AU_RICH_ELEMENTS",	"REACTOME_THE_ROLE_OF_GTSE1_IN_G2_M_PROGRESSION_AFTER_G2_CHECKPOINT",
                           "REACTOME_DOWNSTREAM_SIGNALING_EVENTS_OF_B_CELL_RECEPTOR_BCR",	"REACTOME_CA_DEPENDENT_EVENTS",	"REACTOME_THE_CITRIC_ACID_TCA_CYCLE_AND_RESPIRATORY_ELECTRON_TRANSPORT",	"REACTOME_RHOBTB2_GTPASE_CYCLE",	"REACTOME_CLEC7A_DECTIN_1_INDUCES_NFAT_ACTIVATION",	"REACTOME_REGULATION_OF_RUNX2_EXPRESSION_AND_ACTIVITY",	"REACTOME_YAP1_AND_WWTR1_TAZ_STIMULATED_GENE_EXPRESSION",	"REACTOME_PTEN_REGULATION",	"REACTOME_CYTOPROTECTION_BY_HMOX1",	"REACTOME_DEFECTIVE_CFTR_CAUSES_CYSTIC_FIBROSIS",	"REACTOME_G1_S_DNA_DAMAGE_CHECKPOINTS",	"REACTOME_RHO_GTPASES_ACTIVATE_PAKS",	"REACTOME_CDT1_ASSOCIATION_WITH_THE_CDC6_ORC_ORIGIN_COMPLEX",	"REACTOME_METABOLISM_OF_POLYAMINES",	"REACTOME_APOPTOTIC_CLEAVAGE_OF_CELLULAR_PROTEINS",	"REACTOME_TRANSCRIPTIONAL_REGULATION_BY_RUNX3",
                           "REACTOME_TGF_BETA_RECEPTOR_SIGNALING_IN_EMT_EPITHELIAL_TO_MESENCHYMAL_TRANSITION",	"REACTOME_DOWNREGULATION_OF_TGF_BETA_RECEPTOR_SIGNALING",	"REACTOME_SMOOTH_MUSCLE_CONTRACTION",	"REACTOME_SIGNALING_BY_WNT",	"REACTOME_DECTIN_1_MEDIATED_NONCANONICAL_NF_KB_SIGNALING",	"REACTOME_G_BETA_GAMMA_SIGNALLING_THROUGH_CDC42",	"REACTOME_SCF_SKP2_MEDIATED_DEGRADATION_OF_P27_P21",	"REACTOME_SIGNALING_BY_NOTCH4",	"REACTOME_TCF_DEPENDENT_SIGNALING_IN_RESPONSE_TO_WNT",	"REACTOME_VOLTAGE_GATED_POTASSIUM_CHANNELS",	"REACTOME_TGF_BETA_RECEPTOR_SIGNALING_ACTIVATES_SMADS",	"REACTOME_TRANSCRIPTIONAL_REGULATION_BY_RUNX1",
                           "REACTOME_COOPERATION_OF_PDCL_PHLP1_AND_TRIC_CCT_IN_G_PROTEIN_BETA_FOLDING",	"REACTOME_RHO_GTPASES_ACTIVATE_PKNS",	"REACTOME_APC_C_CDH1_MEDIATED_DEGRADATION_OF_CDC20_AND_OTHER_APC_C_CDH1_TARGETED_PROTEINS_IN_LATE_MITOSIS_EARLY_G1",	"REACTOME_CA2_PATHWAY",	"REACTOME_HSF1_ACTIVATION",	"REACTOME_ABC_TRANSPORTER_DISORDERS",	"REACTOME_SIGNALING_BY_THE_B_CELL_RECEPTOR_BCR",	"REACTOME_CLEC7A_DECTIN_1_SIGNALING",
                           "REACTOME_NEPHRIN_FAMILY_INTERACTIONS",	"REACTOME_ADRENALINE_NORADRENALINE_INHIBITS_INSULIN_SECRETION",	"REACTOME_G_BETA_GAMMA_SIGNALLING_THROUGH_PI3KGAMMA",	"REACTOME_TNFR2_NON_CANONICAL_NF_KB_PATHWAY",	"REACTOME_TRANSCRIPTIONAL_REGULATION_BY_MECP2",	"REACTOME_FCERI_MEDIATED_NF_KB_ACTIVATION",	"REACTOME_APC_C_MEDIATED_DEGRADATION_OF_CELL_CYCLE_PROTEINS",	"REACTOME_MRNA_SPLICING",	"REACTOME_UCH_PROTEINASES",	"REACTOME_RHOBTB_GTPASE_CYCLE",	"REACTOME_GLUCAGON_TYPE_LIGAND_RECEPTORS",	"REACTOME_HOST_INTERACTIONS_OF_HIV_FACTORS",	"REACTOME_COOPERATION_OF_PREFOLDIN_AND_TRIC_CCT_IN_ACTIN_AND_TUBULIN_FOLDING",	"REACTOME_REGULATION_OF_MECP2_EXPRESSION_AND_ACTIVITY",	"REACTOME_ATTENUATION_PHASE",	"REACTOME_TRANSCRIPTIONAL_REGULATION_BY_RUNX2",	"REACTOME_ABC_FAMILY_PROTEINS_MEDIATED_TRANSPORT",	"REACTOME_CELLULAR_RESPONSE_TO_HYPOXIA",	"REACTOME_ANTIGEN_PROCESSING_CROSS_PRESENTATION",	"REACTOME_G_PROTEIN_BETA_GAMMA_SIGNALLING",	"REACTOME_G_ALPHA_Z_SIGNALLING_EVENTS",
                           "REACTOME_STRIATED_MUSCLE_CONTRACTION",	"REACTOME_HEDGEHOG_OFF_STATE",	"REACTOME_HDACS_DEACETYLATE_HISTONES",	"REACTOME_RHO_GTPASES_ACTIVATE_WASPS_AND_WAVES",	"REACTOME_ORC1_REMOVAL_FROM_CHROMATIN",	"REACTOME_FC_EPSILON_RECEPTOR_FCERI_SIGNALING",	"REACTOME_GLUCAGON_LIKE_PEPTIDE_1_GLP1_REGULATES_INSULIN_SECRETION",	"REACTOME_RUNX1_INTERACTS_WITH_CO_FACTORS_WHOSE_PRECISE_EFFECT_ON_RUNX1_TARGETS_IS_NOT_KNOWN",	"REACTOME_SIGNALING_BY_PDGFR_IN_DISEASE",	"REACTOME_CELLULAR_RESPONSE_TO_CHEMICAL_STRESS",	"REACTOME_INTERLEUKIN_12_SIGNALING",	"REACTOME_FGFR2_ALTERNATIVE_SPLICING",
                           "REACTOME_MRNA_SPLICING_MINOR_PATHWAY",	"REACTOME_DEACTIVATION_OF_THE_BETA_CATENIN_TRANSACTIVATING_COMPLEX",	"REACTOME_NCAM_SIGNALING_FOR_NEURITE_OUT_GROWTH",	"REACTOME_SIGNALING_BY_FGFR2",	"REACTOME_SIGNALING_BY_FGFR",	"REACTOME_APOPTOTIC_EXECUTION_PHASE",	"REACTOME_INTERLEUKIN_12_FAMILY_SIGNALING",	"REACTOME_DAP12_INTERACTIONS",	"REACTOME_SIGNALING_BY_TGF_BETA_RECEPTOR_COMPLEX",
                           "REACTOME_ANTIGEN_PRESENTATION_FOLDING_ASSEMBLY_AND_PEPTIDE_LOADING_OF_CLASS_I_MHC",	"REACTOME_RHOBTB1_GTPASE_CYCLE",	"REACTOME_THE_ROLE_OF_NEF_IN_HIV_1_REPLICATION_AND_DISEASE_PATHOGENESIS",	"REACTOME_SEMAPHORIN_INTERACTIONS",	"REACTOME_HSF1_DEPENDENT_TRANSACTIVATION",	"REACTOME_POTENTIAL_THERAPEUTICS_FOR_SARS",	"REACTOME_MAPK_FAMILY_SIGNALING_CASCADES",
                           "REACTOME_CYCLIN_A_CDK2_ASSOCIATED_EVENTS_AT_S_PHASE_ENTRY",	"REACTOME_C_TYPE_LECTIN_RECEPTORS_CLRS",	"REACTOME_DAG_AND_IP3_SIGNALING",	"REACTOME_SIGNALING_BY_FGFR2_IN_DISEASE",	"REACTOME_SIGNALING_BY_HEDGEHOG",	"REACTOME_SYNTHESIS_OF_ACTIVE_UBIQUITIN_ROLES_OF_E1_AND_E2_ENZYMES",	"REACTOME_APOPTOSIS",	"REACTOME_DOWNSTREAM_SIGNAL_TRANSDUCTION",	"REACTOME_SARS_COV_INFECTIONS",	"REACTOME_SIGNALING_BY_ERBB2",	"REACTOME_NOTCH_HLH_TRANSCRIPTION_PATHWAY",	"REACTOME_INTRACELLULAR_SIGNALING_BY_SECOND_MESSENGERS",	"REACTOME_SEPARATION_OF_SISTER_CHROMATIDS",	"REACTOME_PROCESSING_OF_CAPPED_INTRON_CONTAINING_PRE_MRNA",	"REACTOME_UB_SPECIFIC_PROCESSING_PROTEASES",	"REACTOME_NETRIN_1_SIGNALING",
                           "REACTOME_SWITCHING_OF_ORIGINS_TO_A_POST_REPLICATIVE_STATE",	"REACTOME_COSTIMULATION_BY_THE_CD28_FAMILY",	"REACTOME_HSP90_CHAPERONE_CYCLE_FOR_STEROID_HORMONE_RECEPTORS_SHR_IN_THE_PRESENCE_OF_LIGAND",	"REACTOME_SIGNALING_BY_NOTCH",	"REACTOME_DAP12_SIGNALING",	"REACTOME_SUMOYLATION_OF_TRANSCRIPTION_COFACTORS",	"REACTOME_NOTCH1_INTRACELLULAR_DOMAIN_REGULATES_TRANSCRIPTION",	"REACTOME_EPH_EPHRIN_SIGNALING",	"REACTOME_ER_TO_GOLGI_ANTEROGRADE_TRANSPORT",	"REACTOME_SIGNALING_BY_VEGF",	"REACTOME_POSITIVE_EPIGENETIC_REGULATION_OF_RRNA_EXPRESSION",	"REACTOME_SIGNALING_BY_FGFR1",	"REACTOME_RNA_POLYMERASE_II_TRANSCRIPTION_TERMINATION",	"REACTOME_COPI_MEDIATED_ANTEROGRADE_TRANSPORT",	"REACTOME_FCGR3A_MEDIATED_IL10_SYNTHESIS",	"REACTOME_MUSCLE_CONTRACTION",
                           "REACTOME_EPIGENETIC_REGULATION_OF_GENE_EXPRESSION",	"REACTOME_PROTEIN_UBIQUITINATION",	"REACTOME_DISEASES_OF_SIGNAL_TRANSDUCTION_BY_GROWTH_FACTOR_RECEPTORS_AND_SECOND_MESSENGERS",	"REACTOME_PROGRAMMED_CELL_DEATH",	"REACTOME_FCGAMMA_RECEPTOR_FCGR_DEPENDENT_PHAGOCYTOSIS",	"REACTOME_DEADENYLATION_DEPENDENT_MRNA_DECAY",	"REACTOME_TRANSPORT_TO_THE_GOLGI_AND_SUBSEQUENT_MODIFICATION",	"REACTOME_SIGNALING_BY_MET",	"REACTOME_OPIOID_SIGNALLING",	"REACTOME_HIV_INFECTION",	"REACTOME_IMMUNOREGULATORY_INTERACTIONS_BETWEEN_A_LYMPHOID_AND_A_NON_LYMPHOID_CELL",	"REACTOME_PEPTIDE_HORMONE_METABOLISM",	"REACTOME_ESTROGEN_DEPENDENT_GENE_EXPRESSION",
                           "REACTOME_COPI_INDEPENDENT_GOLGI_TO_ER_RETROGRADE_TRAFFIC",	"REACTOME_ONCOGENIC_MAPK_SIGNALING",	"REACTOME_REGULATION_OF_PTEN_GENE_TRANSCRIPTION",	"REACTOME_SIGNALING_BY_ALK_IN_CANCER",	"REACTOME_PARASITE_INFECTION",	"REACTOME_SIGNALING_BY_NOTCH1_PEST_DOMAIN_MUTANTS_IN_CANCER",	"REACTOME_PLATELET_HOMEOSTASIS",	"REACTOME_SIGNALING_BY_TGFB_FAMILY_MEMBERS",	"REACTOME_G_PROTEIN_MEDIATED_EVENTS",	"REACTOME_ESR_MEDIATED_SIGNALING",	"REACTOME_MITOCHONDRIAL_BIOGENESIS",	"REACTOME_DNA_REPLICATION_PRE_INITIATION",	"REACTOME_COPII_MEDIATED_VESICLE_TRANSPORT",
                           "REACTOME_SIGNALING_BY_BRAF_AND_RAF1_FUSIONS",	"REACTOME_DEUBIQUITINATION",	"REACTOME_RAC1_GTPASE_CYCLE",	"REACTOME_TP53_REGULATES_METABOLIC_GENES",	"REACTOME_GOLGI_TO_ER_RETROGRADE_TRANSPORT",	"REACTOME_MITOTIC_METAPHASE_AND_ANAPHASE",	"REACTOME_G2_M_CHECKPOINTS",	"REACTOME_ANTI_INFLAMMATORY_RESPONSE_FAVOURING_LEISHMANIA_PARASITE_INFECTION",	"REACTOME_SUMOYLATION",	"REACTOME_SIGNALING_BY_PDGF",	"REACTOME_S_PHASE",	"REACTOME_SYNTHESIS_OF_DNA",
                           "REACTOME_CIRCADIAN_CLOCK",	"REACTOME_CARDIAC_CONDUCTION",	"REACTOME_PROTEIN_FOLDING",	"REACTOME_TRANSLATION_OF_SARS_COV_2_STRUCTURAL_PROTEINS",	"REACTOME_EXTRA_NUCLEAR_ESTROGEN_SIGNALING",	"REACTOME_RAC2_GTPASE_CYCLE",	"REACTOME_MITOTIC_G2_G2_M_PHASES",	"REACTOME_POTASSIUM_CHANNELS",	"REACTOME_INTERLEUKIN_1_FAMILY_SIGNALING",	"REACTOME_CHROMATIN_MODIFYING_ENZYMES",	"REACTOME_M_PHASE",
                           "REACTOME_MITOTIC_G1_PHASE_AND_G1_S_TRANSITION",	"REACTOME_INTERLEUKIN_1_SIGNALING",	"REACTOME_HCMV_EARLY_EVENTS",	"REACTOME_SARS_COV_2_INFECTION",	"REACTOME_MHC_CLASS_II_ANTIGEN_PRESENTATION",	"REACTOME_HCMV_INFECTION",	"REACTOME_CLATHRIN_MEDIATED_ENDOCYTOSIS",	"REACTOME_SIGNALING_BY_NOTCH1",	"REACTOME_COPI_DEPENDENT_GOLGI_TO_ER_RETROGRADE_TRAFFIC",	"REACTOME_ASPARAGINE_N_LINKED_GLYCOSYLATION",	"REACTOME_RHO_GTPASE_EFFECTORS",	"REACTOME_DNA_REPLICATION",	"REACTOME_RHOA_GTPASE_CYCLE",	"REACTOME_RHO_GTPASE_CYCLE",	"REACTOME_TRANSPORT_OF_MATURE_TRANSCRIPT_TO_CYTOPLASM",
                           "REACTOME_RAB_GEFS_EXCHANGE_GTP_FOR_GDP_ON_RABS",	"REACTOME_NEDDYLATION",	"REACTOME_ANTIGEN_PROCESSING_UBIQUITINATION_PROTEASOME_DEGRADATION",	"REACTOME_CELL_CYCLE_MITOTIC",	"REACTOME_INTRA_GOLGI_AND_RETROGRADE_GOLGI_TO_ER_TRAFFIC",	"REACTOME_G_ALPHA_Q_SIGNALLING_EVENTS",
                           "REACTOME_CELL_CYCLE_CHECKPOINTS",	"REACTOME_NEUROTRANSMITTER_RECEPTORS_AND_POSTSYNAPTIC_SIGNAL_TRANSMISSION",	"REACTOME_LEISHMANIA_INFECTION",	"REACTOME_DISORDERS_OF_TRANSMEMBRANE_TRANSPORTERS",	"REACTOME_SIGNALING_BY_NUCLEAR_RECEPTORS",	"REACTOME_TRANSCRIPTIONAL_REGULATION_BY_TP53",	"REACTOME_SIGNALING_BY_RECEPTOR_TYROSINE_KINASES",
                           "REACTOME_TRANSMISSION_ACROSS_CHEMICAL_SYNAPSES",	"REACTOME_PLATELET_ACTIVATION_SIGNALING_AND_AGGREGATION",	"REACTOME_CLASS_I_MHC_MEDIATED_ANTIGEN_PROCESSING_PRESENTATION",	"REACTOME_HIV_LIFE_CYCLE",	"REACTOME_INTERFERON_SIGNALING",	"REACTOME_DEATH_RECEPTOR_SIGNALLING",
                           "REACTOME_ORGANELLE_BIOGENESIS_AND_MAINTENANCE",	"REACTOME_HEMOSTASIS",	"REACTOME_NEURONAL_SYSTEM")


CD4T_RKPvs.EKP_pos_reactome = c("REACTOME_EUKARYOTIC_TRANSLATION_ELONGATION",	"REACTOME_RESPONSE_OF_EIF2AK4_GCN2_TO_AMINO_ACID_DEFICIENCY",	"REACTOME_SELENOAMINO_ACID_METABOLISM",	"REACTOME_SRP_DEPENDENT_COTRANSLATIONAL_PROTEIN_TARGETING_TO_MEMBRANE",	"REACTOME_EUKARYOTIC_TRANSLATION_INITIATION",	"REACTOME_NONSENSE_MEDIATED_DECAY_NMD",	"REACTOME_INFLUENZA_INFECTION",	"REACTOME_REGULATION_OF_EXPRESSION_OF_SLITS_AND_ROBOS",
                                "REACTOME_SIGNALING_BY_ROBO_RECEPTORS",	"REACTOME_ACTIVATION_OF_THE_MRNA_UPON_BINDING_OF_THE_CAP_BINDING_COMPLEX_AND_EIFS_AND_SUBSEQUENT_BINDING_TO_43S",	"REACTOME_RRNA_PROCESSING",	"REACTOME_CELLULAR_RESPONSE_TO_STARVATION",	"REACTOME_GENERATION_OF_SECOND_MESSENGER_MOLECULES",	"REACTOME_TRANSPORT_OF_ORGANIC_ANIONS",
                                "REACTOME_FORMATION_OF_ATP_BY_CHEMIOSMOTIC_COUPLING",	"REACTOME_NERVOUS_SYSTEM_DEVELOPMENT",	"REACTOME_RUNX3_REGULATES_YAP1_MEDIATED_TRANSCRIPTION",	"REACTOME_RHO_GTPASES_ACTIVATE_PAKS",	"REACTOME_TCR_SIGNALING",	"REACTOME_SEMA3A_PAK_DEPENDENT_AXON_REPULSION",	"REACTOME_NEGATIVE_REGULATION_OF_FLT3",	"REACTOME_MODULATION_BY_MTB_OF_HOST_IMMUNE_SYSTEM",	"REACTOME_METABOLISM_OF_AMINO_ACIDS_AND_DERIVATIVES",	"REACTOME_SIGNALING_BY_EGFR_IN_CANCER",
                                "REACTOME_MUSCLE_CONTRACTION",	"REACTOME_PLATELET_CALCIUM_HOMEOSTASIS",	"REACTOME_YAP1_AND_WWTR1_TAZ_STIMULATED_GENE_EXPRESSION",	"REACTOME_INTERACTION_BETWEEN_L1_AND_ANKYRINS",	"REACTOME_TRANSCRIPTIONAL_REGULATION_BY_MECP2",	"REACTOME_RHOBTB_GTPASE_CYCLE",	"REACTOME_REGULATION_OF_MECP2_EXPRESSION_AND_ACTIVITY",	"REACTOME_ENDOSOMAL_VACUOLAR_PATHWAY",
                                "REACTOME_RHO_GTPASES_ACTIVATE_PKNS",	"REACTOME_RESPIRATORY_ELECTRON_TRANSPORT_ATP_SYNTHESIS_BY_CHEMIOSMOTIC_COUPLING_AND_HEAT_PRODUCTION_BY_UNCOUPLING_PROTEINS",	"REACTOME_SYNTHESIS_OF_IP3_AND_IP4_IN_THE_CYTOSOL",
                                "REACTOME_CONSTITUTIVE_SIGNALING_BY_LIGAND_RESPONSIVE_EGFR_CANCER_VARIANTS",	"REACTOME_RHOBTB2_GTPASE_CYCLE",	"REACTOME_PI_3K_CASCADE_FGFR1",	"REACTOME_ROLE_OF_SECOND_MESSENGERS_IN_NETRIN_1_SIGNALING",	"REACTOME_CRISTAE_FORMATION",	"REACTOME_ANTIGEN_PRESENTATION_FOLDING_ASSEMBLY_AND_PEPTIDE_LOADING_OF_CLASS_I_MHC",
                                "REACTOME_INTERFERON_ALPHA_BETA_SIGNALING",	"REACTOME_TRANSLATION",	"REACTOME_FLT3_SIGNALING_BY_CBL_MUTANTS",	"REACTOME_NEF_AND_SIGNAL_TRANSDUCTION",	"REACTOME_SIGNALING_BY_NOTCH1_HD_DOMAIN_MUTANTS_IN_CANCER",	"REACTOME_NCAM_SIGNALING_FOR_NEURITE_OUT_GROWTH",	"REACTOME_REGULATION_OF_FZD_BY_UBIQUITINATION",	"REACTOME_SMOOTH_MUSCLE_CONTRACTION",
                                "REACTOME_RHO_GTPASES_ACTIVATE_WASPS_AND_WAVES",	"REACTOME_RAP1_SIGNALLING",	"REACTOME_HOST_INTERACTIONS_OF_HIV_FACTORS",	"REACTOME_NETRIN_1_SIGNALING",	"REACTOME_NOTCH1_INTRACELLULAR_DOMAIN_REGULATES_TRANSCRIPTION",	"REACTOME_DOWNSTREAM_SIGNALING_EVENTS_OF_B_CELL_RECEPTOR_BCR",	"REACTOME_CARDIAC_CONDUCTION",	"REACTOME_INTERLEUKIN_7_SIGNALING",	"REACTOME_EPHB_MEDIATED_FORWARD_SIGNALING",
                                "REACTOME_REGULATION_OF_TNFR1_SIGNALING",	"REACTOME_PCP_CE_PATHWAY",	"REACTOME_SIGNALING_BY_FGFR1",	"REACTOME_BETA_CATENIN_INDEPENDENT_WNT_SIGNALING",	"REACTOME_SEMAPHORIN_INTERACTIONS",	"REACTOME_SUMOYLATION_OF_TRANSCRIPTION_COFACTORS",	"REACTOME_RESPIRATORY_ELECTRON_TRANSPORT",
                                "REACTOME_THE_ROLE_OF_NEF_IN_HIV_1_REPLICATION_AND_DISEASE_PATHOGENESIS",	"REACTOME_IMMUNOREGULATORY_INTERACTIONS_BETWEEN_A_LYMPHOID_AND_A_NON_LYMPHOID_CELL",	"REACTOME_CA2_PATHWAY",	"REACTOME_REGULATION_OF_RUNX2_EXPRESSION_AND_ACTIVITY",	"REACTOME_COSTIMULATION_BY_THE_CD28_FAMILY",	"REACTOME_REGULATION_OF_RAS_BY_GAPS",	"REACTOME_SIGNALING_BY_THE_B_CELL_RECEPTOR_BCR",	"REACTOME_AUF1_HNRNP_D0_BINDS_AND_DESTABILIZES_MRNA",	"REACTOME_SIGNALING_BY_WNT",
                                "REACTOME_SIGNALING_BY_NOTCH1_PEST_DOMAIN_MUTANTS_IN_CANCER",	"REACTOME_RUNX1_REGULATES_TRANSCRIPTION_OF_GENES_INVOLVED_IN_DIFFERENTIATION_OF_HSCS",	"REACTOME_UCH_PROTEINASES",	"REACTOME_DECTIN_1_MEDIATED_NONCANONICAL_NF_KB_SIGNALING",	"REACTOME_DEGRADATION_OF_GLI1_BY_THE_PROTEASOME",	"REACTOME_ASYMMETRIC_LOCALIZATION_OF_PCP_PROTEINS",	"REACTOME_MAPK6_MAPK4_SIGNALING",
                                "REACTOME_CHROMATIN_MODIFYING_ENZYMES",	"REACTOME_SIGNALING_BY_TGF_BETA_RECEPTOR_COMPLEX",	"REACTOME_NEGATIVE_REGULATION_OF_NOTCH4_SIGNALING",	"REACTOME_DEGRADATION_OF_BETA_CATENIN_BY_THE_DESTRUCTION_COMPLEX",	"REACTOME_TNFR2_NON_CANONICAL_NF_KB_PATHWAY",	"REACTOME_TCF_DEPENDENT_SIGNALING_IN_RESPONSE_TO_WNT",	"REACTOME_PTEN_REGULATION",	"REACTOME_DEGRADATION_OF_AXIN",	"REACTOME_POTENTIAL_THERAPEUTICS_FOR_SARS",	"REACTOME_HEDGEHOG_ON_STATE",	"REACTOME_TRANSCRIPTIONAL_REGULATION_BY_RUNX1",	"REACTOME_CLEC7A_DECTIN_1_SIGNALING",
                                "REACTOME_REGULATION_OF_MRNA_STABILITY_BY_PROTEINS_THAT_BIND_AU_RICH_ELEMENTS",	"REACTOME_MAPK_FAMILY_SIGNALING_CASCADES",	"REACTOME_SARS_COV_INFECTIONS",	"REACTOME_FCGAMMA_RECEPTOR_FCGR_DEPENDENT_PHAGOCYTOSIS",	"REACTOME_SIGNALING_BY_MET",	"REACTOME_SIGNALING_BY_VEGF",	"REACTOME_INTERFERON_SIGNALING",	"REACTOME_MITOCHONDRIAL_BIOGENESIS",	"REACTOME_HEDGEHOG_OFF_STATE",	"REACTOME_INTERFERON_GAMMA_SIGNALING",	"REACTOME_CYTOPROTECTION_BY_HMOX1",	"REACTOME_PLATELET_HOMEOSTASIS",	"REACTOME_APC_C_MEDIATED_DEGRADATION_OF_CELL_CYCLE_PROTEINS",	"REACTOME_FC_EPSILON_RECEPTOR_FCERI_SIGNALING",	"REACTOME_RAC1_GTPASE_CYCLE",	"REACTOME_ABC_FAMILY_PROTEINS_MEDIATED_TRANSPORT",	"REACTOME_APOPTOSIS",
                                "REACTOME_TRANSCRIPTIONAL_REGULATION_BY_RUNX2",	"REACTOME_RHOA_GTPASE_CYCLE",	"REACTOME_RHO_GTPASE_CYCLE",	"REACTOME_SUMOYLATION",	"REACTOME_SIGNALING_BY_HEDGEHOG",	"REACTOME_CLATHRIN_MEDIATED_ENDOCYTOSIS",	"REACTOME_ORGANELLE_BIOGENESIS_AND_MAINTENANCE",	"REACTOME_THE_CITRIC_ACID_TCA_CYCLE_AND_RESPIRATORY_ELECTRON_TRANSPORT",
                                "REACTOME_SEPARATION_OF_SISTER_CHROMATIDS",	"REACTOME_MRNA_SPLICING",	"REACTOME_MITOTIC_METAPHASE_AND_ANAPHASE",	"REACTOME_HIV_INFECTION",	"REACTOME_PROGRAMMED_CELL_DEATH",	"REACTOME_INTRACELLULAR_SIGNALING_BY_SECOND_MESSENGERS",
                            "REACTOME_DISEASES_OF_SIGNAL_TRANSDUCTION_BY_GROWTH_FACTOR_RECEPTORS_AND_SECOND_MESSENGERS",	"REACTOME_PROCESSING_OF_CAPPED_INTRON_CONTAINING_PRE_MRNA",	"REACTOME_RHO_GTPASE_EFFECTORS",	"REACTOME_SIGNALING_BY_NOTCH",	"REACTOME_M_PHASE",	"REACTOME_CELL_CYCLE_MITOTIC")

data_3 = CD8T_RKPvs.EKP_pos_reactome 
data_4 = CD4T_RKPvs.EKP_pos_reactome

set3 = as.list(data_3)
set4 = as.list(data_4)

venn.diagram(
  x = list(set3, set4),
  category.names = c("" , ""),
  filename = 'RKP_CD8T_and_CD4T_positive_REACTOME_venn_diagramm.png',
  output=TRUE,
  
  # Output features
  imagetype="png" ,
  height = 480 , 
  width = 480 , 
  resolution = 300,
  compression = "lzw",
  
  # Circles
  lwd = 2,
  lty = 'blank',
  fill = c('lightpink2','lightseagreen'),
  cat.pos=c(2, 5),
  # Numbers
  cex = .6,
  fontface = "bold",
  fontfamily = "sans"
)


#fgsea: KEGG results comparison


CD8T_RKPvs.EKP_pos_KEGG = c("KEGG_RIBOSOME",	"KEGG_PARKINSONS_DISEASE",	"KEGG_CARDIAC_MUSCLE_CONTRACTION",	"KEGG_PROTEASOME",	"KEGG_OXIDATIVE_PHOSPHORYLATION",	"KEGG_ALZHEIMERS_DISEASE",	"KEGG_PRIMARY_IMMUNODEFICIENCY",	"KEGG_HUNTINGTONS_DISEASE",	"KEGG_PROXIMAL_TUBULE_BICARBONATE_RECLAMATION",
                            "KEGG_T_CELL_RECEPTOR_SIGNALING_PATHWAY",	"KEGG_AXON_GUIDANCE",	"KEGG_VIRAL_MYOCARDITIS",	"KEGG_NATURAL_KILLER_CELL_MEDIATED_CYTOTOXICITY",	"KEGG_GRAFT_VERSUS_HOST_DISEASE",	"KEGG_PROTEIN_EXPORT",	"KEGG_ALLOGRAFT_REJECTION",	"KEGG_SPLICEOSOME",
                            "KEGG_PATHOGENIC_ESCHERICHIA_COLI_INFECTION",	"KEGG_AUTOIMMUNE_THYROID_DISEASE",	"KEGG_WNT_SIGNALING_PATHWAY",	"KEGG_NON_SMALL_CELL_LUNG_CANCER",	"KEGG_COLORECTAL_CANCER",
                            "KEGG_LEUKOCYTE_TRANSENDOTHELIAL_MIGRATION",	"KEGG_ENDOMETRIAL_CANCER",	"KEGG_CELL_ADHESION_MOLECULES_CAMS",	"KEGG_CITRATE_CYCLE_TCA_CYCLE",	"KEGG_OLFACTORY_TRANSDUCTION",	"KEGG_VEGF_SIGNALING_PATHWAY",	"KEGG_TYPE_I_DIABETES_MELLITUS",	"KEGG_ANTIGEN_PROCESSING_AND_PRESENTATION",	"KEGG_LONG_TERM_POTENTIATION",	"KEGG_REGULATION_OF_ACTIN_CYTOSKELETON",
                            "KEGG_VASCULAR_SMOOTH_MUSCLE_CONTRACTION",	"KEGG_FOCAL_ADHESION",	"KEGG_ERBB_SIGNALING_PATHWAY",	"KEGG_NEUROTROPHIN_SIGNALING_PATHWAY",	"KEGG_TIGHT_JUNCTION",	"KEGG_BASAL_CELL_CARCINOMA",	"KEGG_GAP_JUNCTION",	"KEGG_OOCYTE_MEIOSIS",	"KEGG_CALCIUM_SIGNALING_PATHWAY",	"KEGG_ADHERENS_JUNCTION",	"KEGG_PANCREATIC_CANCER",	"KEGG_UBIQUITIN_MEDIATED_PROTEOLYSIS",
                            "KEGG_DILATED_CARDIOMYOPATHY",	"KEGG_FC_GAMMA_R_MEDIATED_PHAGOCYTOSIS",	"KEGG_GNRH_SIGNALING_PATHWAY",	"KEGG_MELANOGENESIS",	"KEGG_ARRHYTHMOGENIC_RIGHT_VENTRICULAR_CARDIOMYOPATHY_ARVC",	"KEGG_B_CELL_RECEPTOR_SIGNALING_PATHWAY",	"KEGG_PATHWAYS_IN_CANCER",	"KEGG_CHEMOKINE_SIGNALING_PATHWAY")


CD4T_RKPvs.EKP_pos_KEGG = c("KEGG_RIBOSOME",	"KEGG_PARKINSONS_DISEASE",	"KEGG_T_CELL_RECEPTOR_SIGNALING_PATHWAY",	"KEGG_PRIMARY_IMMUNODEFICIENCY",	"KEGG_NATURAL_KILLER_CELL_MEDIATED_CYTOTOXICITY",	"KEGG_AXON_GUIDANCE",	"KEGG_VIRAL_MYOCARDITIS",	"KEGG_CARDIAC_MUSCLE_CONTRACTION",	"KEGG_ALZHEIMERS_DISEASE",	"KEGG_ANTIGEN_PROCESSING_AND_PRESENTATION",	"KEGG_PHOSPHATIDYLINOSITOL_SIGNALING_SYSTEM",
                            "KEGG_LEUKOCYTE_TRANSENDOTHELIAL_MIGRATION",	"KEGG_DILATED_CARDIOMYOPATHY",	"KEGG_HEDGEHOG_SIGNALING_PATHWAY",	"KEGG_VASCULAR_SMOOTH_MUSCLE_CONTRACTION",	"KEGG_LONG_TERM_POTENTIATION",	"KEGG_REGULATION_OF_ACTIN_CYTOSKELETON",	"KEGG_HUNTINGTONS_DISEASE",	"KEGG_FOCAL_ADHESION",	"KEGG_VEGF_SIGNALING_PATHWAY",	"KEGG_HYPERTROPHIC_CARDIOMYOPATHY_HCM",	"KEGG_WNT_SIGNALING_PATHWAY",
                            "KEGG_CALCIUM_SIGNALING_PATHWAY",	"KEGG_PROTEASOME",	"KEGG_CELL_ADHESION_MOLECULES_CAMS",	"KEGG_ERBB_SIGNALING_PATHWAY",	"KEGG_OOCYTE_MEIOSIS",	"KEGG_NEUROTROPHIN_SIGNALING_PATHWAY",	"KEGG_MAPK_SIGNALING_PATHWAY")

data_5 = CD8T_RKPvs.EKP_pos_KEGG 
data_6 = CD4T_RKPvs.EKP_pos_KEGG

set5 = as.list(data_5)
set6 = as.list(data_6)

venn.diagram(
  x = list(set5, set6),
  category.names = c("" , ""),
  filename = 'RKP_CD8T_and_CD4T_positive_KEGG_venn_diagramm.png',
  output=TRUE,
  
  # Output features
  imagetype="png" ,
  height = 480 , 
  width = 480 , 
  resolution = 300,
  compression = "lzw",
  
  # Circles
  lwd = 2,
  lty = 'blank',
  fill = c('lightpink2','lightseagreen'),
  cat.pos=c(-10, 0),
  # Numbers
  cex = .6,
  fontface = "bold",
  fontfamily = "sans"
)








GOBP_intersect= as.data.frame(Reduce(intersect, list(set1,set2)))
GOBP_intersect =t(GOBP_intersect)
REACTOME_intersect = as.data.frame(Reduce(intersect, list(set3,set4)))
REACTOME_intersect=t(REACTOME_intersect)
KEGG_intersect = as.data.frame(Reduce(intersect, list(set5,set6)))
KEGG_intersect = t(KEGG_intersect)

n<-max(length(GOBP_intersect),length(REACTOME_intersect),length(KEGG_intersect))
length(GOBP_intersect)<-n
length(KEGG_intersect)<-n

RKP_Tcell_pos = as.data.frame(cbind(GOBP_intersect,REACTOME_intersect,KEGG_intersect))
RKP_Tcell_pos$REACTOME_intersect = RKP_Tcell_pos$V2

write.csv(RKP_Tcell_pos, "intersect_CD8T_CD4T_cell.csv")
